<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\Setting;

class ApiSettingsSeeder extends Seeder
{
    /**
     * Seed API settings from backup
     * These are the production/sandbox credentials from the backup file
     */
    public function run()
    {
        $this->command->info('Seeding API settings from backup...');

        // Woohoo API Settings (from backup)
        $this->createOrUpdateSetting([
            'key' => 'api.woohoo_url',
            'display_name' => 'Woohoo API Base URL',
            'value' => 'sandbox.woohoo.in',
            'details' => json_encode(['description' => 'Base URL for Woohoo API (without https://)']),
            'type' => 'text',
            'order' => 11,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.qs_username',
            'display_name' => 'Woohoo Username',
            'value' => 'freneticapisandbox@woohoo.in',
            'details' => json_encode(['description' => 'Username for Woohoo API authentication']),
            'type' => 'text',
            'order' => 7,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.qs_password',
            'display_name' => 'Woohoo Password',
            'value' => 'freneticapisandbox@1234',
            'details' => json_encode(['description' => 'Password for Woohoo API authentication']),
            'type' => 'password',
            'order' => 8,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.clientId',
            'display_name' => 'Woohoo Client ID',
            'value' => '546300637c4f1caf36daeeb4a10443f6',
            'details' => json_encode(['description' => 'Client ID for Woohoo API authentication']),
            'type' => 'text',
            'order' => 9,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.qs_clientSecret',
            'display_name' => 'Woohoo Client Secret',
            'value' => 'fb3e12b2e1f526b68ff41b79152be092',
            'details' => json_encode(['description' => 'Client Secret for Woohoo API']),
            'type' => 'text',
            'order' => 10,
            'group' => 'API',
        ]);

        // Bearer Token (will be regenerated by command)
        $this->createOrUpdateSetting([
            'key' => 'api.bearer_token',
            'display_name' => 'Bearer Token',
            'value' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb25zdW1lcklkIjo0MjksImV4cCI6MTc0NTE3NzQwMiwidG9rZW4iOiJhYmE4ZTJlMzE4Nzg5YjlhOTgxZWM4NzI5MzhiMmJmMSJ9.d1DPdFt4pm-TIbCprk4R6oYoYtxl-t5jsNnzcldkECk',
            'details' => json_encode(['update_time' => '2025-04-14 01:00:02']),
            'type' => 'text',
            'order' => 12,
            'group' => 'API',
        ]);

        // KGen API Settings (placeholders - configure as needed)
        $this->createOrUpdateSetting([
            'key' => 'api.kgen_base_url',
            'display_name' => 'KGen API Base URL',
            'value' => 'https://stage-platform.getkgen.com',
            'details' => json_encode(['description' => 'Base URL for KGen API']),
            'type' => 'text',
            'order' => 20,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.kgen_api_key',
            'display_name' => 'KGen API Key',
            'value' => '',
            'details' => json_encode(['description' => 'API Key for KGen authentication']),
            'type' => 'text',
            'order' => 21,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.kgen_tenant_id',
            'display_name' => 'KGen Tenant ID',
            'value' => '',
            'details' => json_encode(['description' => 'Tenant ID for KGen API']),
            'type' => 'text',
            'order' => 22,
            'group' => 'API',
        ]);

        // Lysto API Settings (placeholders - configure as needed)
        $this->createOrUpdateSetting([
            'key' => 'api.lysto_base_url',
            'display_name' => 'Lysto API Base URL',
            'value' => '',
            'details' => json_encode(['description' => 'Base URL for Lysto API']),
            'type' => 'text',
            'order' => 30,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.lysto_api_key',
            'display_name' => 'Lysto API Key',
            'value' => '',
            'details' => json_encode(['description' => 'API Key for Lysto authentication']),
            'type' => 'text',
            'order' => 31,
            'group' => 'API',
        ]);

        // Value Design API Settings (placeholders - configure as needed)
        $this->createOrUpdateSetting([
            'key' => 'api.value_design_base_url',
            'display_name' => 'Value Design API Base URL',
            'value' => '',
            'details' => json_encode(['description' => 'Base URL for Value Design API']),
            'type' => 'text',
            'order' => 40,
            'group' => 'API',
        ]);

        $this->createOrUpdateSetting([
            'key' => 'api.value_design_api_key',
            'display_name' => 'Value Design API Key',
            'value' => '',
            'details' => json_encode(['description' => 'API Key for Value Design authentication']),
            'type' => 'text',
            'order' => 41,
            'group' => 'API',
        ]);

        $this->command->info('✅ API settings seeded successfully!');
        $this->command->info('');
        $this->command->info('📝 Woohoo API Credentials (Sandbox):');
        $this->command->info('   Base URL: sandbox.woohoo.in');
        $this->command->info('   Username: freneticapisandbox@woohoo.in');
        $this->command->info('   Password: freneticapisandbox@1234');
        $this->command->info('   Client ID: 546300637c4f1caf36daeeb4a10443f6');
        $this->command->info('   Client Secret: fb3e12b2e1f526b68ff41b79152be092');
        $this->command->info('');
        $this->command->info('⚠️  Note: KGen, Lysto, and Value Design API settings are empty.');
        $this->command->info('   Please configure them in Admin -> Settings if needed.');
    }

    /**
     * Create or update a setting
     */
    protected function createOrUpdateSetting($data)
    {
        $setting = Setting::firstOrNew(['key' => $data['key']]);
        
        // Only update if value is not empty or if it's a new setting
        if (!$setting->exists || empty($setting->value) || !empty($data['value'])) {
            $setting->fill($data)->save();
        }
    }
}
