/** Public storefront URL helpers (no Ziggy dependency). */

export const paths = {
    home: '/',
    search: '/search',
    searchSuggest: '/search/suggest',
    business: '/business',
    login: '/login',
    profile: '/profile',
    cart: '/cart',
    cartClear: '/cart/clear',
    cartRemove: '/cart/remove',
    myOrders: '/my-order',
    about: '/about',
    contact: '/contact-us',
    terms: '/terms-of-use',
    privacy: '/privacy-policy',
    refund: '/refund-policy',
    faq: '/faq',
    cardBalance: '/card-balance',
    product: (slug: string) => `/product/${encodeURIComponent(slug)}`,
    category: (slug: string) => `/category/${encodeURIComponent(slug)}`,
    brand: (slug: string) => `/brand/${encodeURIComponent(slug)}`,
    checkout: (slug: string) => `/checkout/${encodeURIComponent(slug)}`,
    cartAdd: (slug: string) => `/cart/${encodeURIComponent(slug)}`,
    verifyEmail: '/verify-email',
    changePassword: '/change-password',
    paymentCcavenue: '/payment/ccavenue',
    paymentRazorpay: '/payment/razorpay',
    paymentRazorpayVerify: '/payment/razorpay/verify',
    paymentMockRazorpay: '/payment/mock-razorpay',
    paymentUnlimit: '/payment/unlimit',
    paymentUpi: '/payment/upi',
    paymentNetbank: '/payment/netbank',
    panel: '/panel',
};
